import { WeatherForcastProvider } from '@/providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/header';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={inter.style}
        className="bg-background text-foreground"
      >
        <WeatherForcastProvider>
          <Header />
          {children}
        </WeatherForcastProvider>
      </body>
    </html>
  );
}

